---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.8.0


executors:
  # Whenever the Go version is updated here, .promu.yml should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.15

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: make
    - prometheus/store_artifact:
        file: pushgateway
  publish-runai:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run:
         command: |-
           echo "export DOCKER_LOGIN=_json_key" >> $BASH_ENV
           echo "export DOCKER_PASSWORD=\`echo $STAGING_GCLOUD_SERVICE_JSON_CONTENT | base64 -d\`" >> $BASH_ENV
           echo "export DOCKER_HOST=gcr.io" >> $BASH_ENV
    - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin gcr.io
    - prometheus/publish_images:
        login_variable: DOCKER_LOGIN
        organization: run-ai
        password_variable: DOCKER_PASSWORD
        registry: gcr.io
workflows:
  version: 2
  pushgateway:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        requires:
        - test
        - build
        docker_hub_organization: ''
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
    - publish-runai:
        requires:
#        - prometheus/publish_release
        - test
        - build
